### ISSUE TITLE
`chalk --help` does not print usage information

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#11]
### Expected behavior

I expected `chalk --help` and `chalk -h` to print usage information, just like `chalk help` and `--help` elsewhere:

```console
$ chalk help | grep cmdname
  •  chalk help "cmdname"  shows the help for an individual command, as does chalk "cmdname" --help
```

### Observed behavior

`chalk --help` and `chalk -h` perform a documentation search.

```console
$ chalk version --no-color | grep commit
┋ Commit ID     ┋ ea36ce1c185731bba9ba191bc1a209a1da2bf6c1 ┋
$ chalk --help | head -n1
SEARCHING DOCUMENTATION FOR TERM: --HELP
```

Is this intended?

**Comment by viega** [comment]
Sorry, that's confusing. The default command if you don't provide one is set to `help` so it basically calls `chalk help --help`; the help command doesn't take flag arguments so that it can show you help on any arguments.

So it's basically only happening when help is the default command, because no other command was provided.
I think the proper thing here is probably to just give usage instead of having a default command set, but would love feedback there.

**Comment by viega** [comment]
The above PR will fix, and I realized here that there's a related usability issue `--help` when the default command is set to any other command will give the command's help not the global help, so the PR also changes that behavior, and gives the global help any time it sees the `--help` flag, unless the command is explicitly provided.
