### ISSUE TITLE
Consider pinning CI dependencies more strictly

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#142]
Currently, this is possible:

1. CI passes on a PR
2. We merge the PR
3. CI fails on `main`

I suggest that we should minimize the possibility of this because:

- CI should always be passing on `main`
- PRs are harder to review when there are unrelated CI failures
- It causes a context switch - CI should be fixed before other PRs can be merged

Recently, for example, CI passed on PR https://github.com/crashappsec/chalk/pull/135 but then failed on `main` with https://github.com/crashappsec/chalk/commit/f496958f9e3078f7f52b5e84bfdce5847dee6f26. @miki725 says it's because a new version of semgrep was released. This also caused CI to fail in PR https://github.com/crashappsec/chalk/pull/137.

In this case, can we pin the versions of dependencies like semgrep, and have automated PRs to update them?

Alternatively, the problem is alleviated somewhat if we use a merge queue.

**Comment by miki725** [comment]
We actually already do that:

All test deps are pinned in https://github.com/crashappsec/chalk/blob/main/tests/pyproject.toml
All system test deps are pinned in https://github.com/crashappsec/chalk/blob/main/tests/Dockerfile

`semgrep` is test is special as `chalk` itself installs it as per `sast_config` during `insert/build` operations:

https://github.com/crashappsec/chalk/blob/991a87f989965994bede3539e793b859ff1ced47/src/configs/sastconfig.c4m#L45-L68

As such tests indirectly install it via chalk which I think is good as it tests whether chalk can correctly install/use the tool as per the config. The bigger issue was that the test was asserting full output payload of the semgrep tool which included its version. At the time when the test case was added in https://github.com/crashappsec/chalk/pull/129 `ContainsMixin` did not have the capability to correctly handle nested lists which semgrep output had which is why full payload was asserted (@indecisivedragon brought that up outside of GitHub). As part of fixing the `main`, now we now have the capability to do partial assertions including on lists and therefore any similar tests in the future can be written better from the start.

Not sure if you have anything else in scope for this issue?

**Comment by miki725** [comment]
closing for now. feel free to reopen if the issue was not answered/addressed
